### ISSUE TITLE
webview flutter版本兼容问题

### ISSUE THREAD

**Issue by keegan-z** [epoll-j/flutter_jsbridge_plugin#6]
问题日志：Because flutter_jsbridge_plugin >=0.0.4 depends on webview_flutter ^1.0.7 and flutter_html 2.1.0 depends on webview_flutter ^2.0.4, flutter_jsbridge_plugin >=0.0.4 is incompatible with flutter_html 2.1.0.
And because no versions of flutter_html match >2.1.0 <3.0.0, flutter_jsbridge_plugin >=0.0.4 is incompatible with flutter_html ^2.1.0.

描述：依赖之后，和其他库冲突

**Comment by applebest** [comment]
同样遇到了这个问题

Because flutter_jsbridge_plugin >=0.0.4 depends on webview_flutter ^1.0.7 and flutter_app depends on webview_flutter 2.0.7, flutter_jsbridge_plugin >=0.0.4 is forbidden.
So, because flutter_app depends on flutter_jsbridge_plugin ^0.0.4, version solving failed.
pub get failed (1; So, because flutter_app depends on flutter_jsbridge_plugin ^0.0.4, version solving failed.)

**Comment by xiaomaxuetu** [comment]
> 问题日志：Because flutter_jsbridge_plugin >=0.0.4 depends on webview_flutter ^1.0.7 and flutter_html 2.1.0 depends on webview_flutter ^2.0.4, flutter_jsbridge_plugin >=0.0.4 is incompatible with flutter_html 2.1.0.
> And because no versions of flutter_html match >2.1.0 <3.0.0, flutter_jsbridge_plugin >=0.0.4 is incompatible with flutter_html ^2.1.0.
> 
> 描述：依赖之后，和其他库冲突
https://github.com/xiaomaxuetu/flutter_jsbridge_plugin 试试这个，改了下可以用

**Comment by epoll-j** [comment]
0.0.5版本已修复该问题
```
dependencies:
  flutter_jsbridge_plugin: ^0.0.5
```
